import "../components/PlacesStyles.css";
import PlacesData from "./PlacesData";

function RajasthanPlaces() {
  return (
    <div className="places">
      <h1>Popular Destinations!</h1>
      <p>You can explore the best.</p>
      <div className="Placescard">
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/new_dest_imagemar/mmt/activities/m_Udaipur_4_l_800_1200.jpg"
          placeName="Udaipur"
          review="4.8"
          price="$350"
          linkTo="/udaipur"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/DestMainImgLscape/mmt/activities/m_Jaipur_1_l_787_1181.jpg"
          placeName="Jaipur"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/m_Neemrana_tv_destination_img_2_l_641_961.jpg"
          placeName="Nimrana"
          review="4.9"
          price="$500"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/bharatpurgalleryimgs/mmt/activities/m_Bharatpur_6_l_666_1000.jpg"
          placeName="Bharatpur"
          review="4.0"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Mount_Abu_tv_destination_img_2_l_824_1098.jpg"
          placeName="Mount Abu"
          review="4.8"
          price="$500"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/m_Jodhpur_destinatoin_tv_image_2_l_900_1350.jpg"
          placeName="Jodhpur"
          review="4.7"
          price="$320"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Jaisalmer_tv_destination_img_7_l_660_988.jpg"
          placeName="Jaisalmer"
          review="4.2"
          price="$300"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/sariska/mmt/destination/m_Sariska_wildlife2_l_423_634.jpg"
          placeName="Sariska Tiger Reserve"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Pushkar_tv_destination_img_5_l_687_1222.jpg"
          placeName="Pushkar"
          review="4.3"
          price="$350"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/tvdestinationimages/mmt/activities/m_Alwar_tv_destination_img_4_l_892_1332.jpg"
          placeName="Alwar"
          review="4.5"
          price="$340"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Ranthambore_tv_destination_img_3_l_859_1288.jpg"
          placeName="Ranthambore"
          review="4.7"
          price="$400"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/m_Ajmer_tv_destination_img_7_l_727_1090.jpg"
          placeName="Ajmer"
          review="4.1"
          price="$380"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/tvdestinationimages/mmt/activities/m_Kumbhalgarh_tv_destination_img_2_l_808_1210.jpg"
          placeName="Kumbhalgarh"
          review="4.8"
          price="$410"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/tvdestinationimages/mmt/activities/m_Nathdwara_tv_destination_img_2_l_667_1000.jpg"
          placeName="Nathdwara"
          review="4.3"
          price="$390"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/chittorgarh/mmt/destination/m_Chittorgarh_l_518_783.jpg"
          placeName="Chittorgarh"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/activities/m_Destinatoin_img_Kota_3_l_605_1060.jpg"
          placeName="Kota"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/Sikar%20to%20Solapur/mmt/activities/m_Sikar_1_l_417_639.jpg"
          placeName="Sikar"
          review="4.6"
          price="$420"
          linkTo="/"
        /> 
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/Kishangarh/mmt/activities/m_Kishangarh_1_l_360_640.jpg"
          placeName="Kishangarh"
          review="4.6"
          price="$420"
          linkTo="/"
        /> 
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/imgs_coll_dest/mmt/activities/m_mandawa_dest_img_l_533_938.jpg"
          placeName="Mandawa"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/activities/m_Destinatoin_img_Bikaner_3_l_502_669.jpg"
          placeName="Bikaner"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/Jhunjhunu%20to%20Junagadh/mmt/activities/m_Jhunjhunu_1_l_364_639.jpg"
          placeName="Jhunjhunu"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/Bhilwara/mmt/activities/m_Bhilwara_1_l_3120_4160.jpg"
          placeName="Bhilwara"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/activities/m_Bundi_destination_landscape_1_l_667_1000.jpg"
          placeName="Bundi"
          review="4.6"
          price="$420"
          linkTo="/"
        />
        <PlacesData
          image="https://hblimg.mmtcdn.com/content/hubble/img/destgalleryimages/mmt/activities/m_Churu_1_l_439_1000.jpg"
          placeName="Churu"
          review="4.6"
          price="$420"
          linkTo="/"
        />
      </div>
    </div>
  );
}

export default RajasthanPlaces;
